FROM continuumio/anaconda3

# install dependencies for spinning up
RUN apt-get update --fix-missing && \
    apt-get install -y g++ gcc libopenmpi-dev vim

RUN mkdir -p home/workspace/ && \
    cd home/workspace/ && git clone https://github.com/openai/spinningup && \
    cd spinningup && \
    pip install pyqt5==5.12 && \
    pip install -e . && \
    chmod -R 777 /home/workspace/
    
# switch user since mpi command could not run as root
RUN  adduser --disabled-password --gecos "" zc114
USER zc114
RUN cd /home/workspace/spinningup && \
    nohup python spinup/examples/bench_ppo_cartpole.py --cpu 2 > test.log &; wait

